# Generated by Django 2.2.5 on 2019-09-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('model_enginee', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=100)),
                ('model_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Producer')),
            ],
        ),
    ]
